name = "CurveFit"
uuid = "978cff62-e2b8-11e8-229c-571aaacc4ba3"
authors = ["Nicholas Timmons <ngtimmons@gmail.com>"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
